//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IncidentesAI.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.14.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string UltimoCaminhoBanco {
            get {
                return ((string)(this["UltimoCaminhoBanco"]));
            }
            set {
                this["UltimoCaminhoBanco"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string UltimoCaminhoExcel {
            get {
                return ((string)(this["UltimoCaminhoExcel"]));
            }
            set {
                this["UltimoCaminhoExcel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DataUltimaImportacao {
            get {
                return ((string)(this["DataUltimaImportacao"]));
            }
            set {
                this["DataUltimaImportacao"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"Você é um analista de dados sênior especializado em Service Desk e gestão de incidentes de TI. Seu papel é analisar a lista COMPLETA de tickets fornecida abaixo e responder às perguntas de forma técnica e precisa.

REGRAS DE FORMATAÇÃO (CRÍTICO):
1. RESPONDA APENAS EM TEXTO PURO.
2. NUNCA USE NEGRITO (não use asteriscos como **exemplo**).
3. NÃO USE Markdown, tabelas, itálico ou símbolos especiais.
4. Use apenas quebras de linha simples (Enter) para separar os parágrafos.

REGRAS DE ANÁLISE DE DADOS:
- As datas dos tickets estão no formato brasileiro (DD/MM/YYYY). 
- Considere que a data atual é 23 de Janeiro de 2026. Portanto, tickets de Janeiro de 2026 são os mais recentes e devem ser priorizados se a pergunta for sobre atualidade.
- Analise CADA LINHA do contexto enviado antes de dizer que um dado não existe.
- Se o usuário perguntar ""Quantos"", responda com o número exato seguido de uma breve listagem, se relevante.
- Seja direto, objetivo e profissional.

Dados dos Incidentes:")]
        public string PromptIA {
            get {
                return ((string)(this["PromptIA"]));
            }
            set {
                this["PromptIA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double TemperaturaIA {
            get {
                return ((double)(this["TemperaturaIA"]));
            }
            set {
                this["TemperaturaIA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int NumeroIncidentes {
            get {
                return ((int)(this["NumeroIncidentes"]));
            }
            set {
                this["NumeroIncidentes"] = value;
            }
        }
    }
}
